config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index', as: :dashboards
  resources :registrations , only: [:new, :create]
  resources :logins , only: [:new, :create]
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true

    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    user = User.find_by(id: session[:user_id])
    redirect_to new_login_path unless user
    @user = user
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
    @user = User.new
  end

  def create
    @user = User.find_by(user_params)
    if @user
      session[:user_id] = @user.id
      redirect_to dashboards_path
    else
      flash[:alert] = "Unable to Login!"
      render :new, status: :unprocessable_entity
    end
  end

  private 
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to new_login_path unless user
    @user = user
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
      flash[:alert] = "Your post has been successfully saved"
    else
      flash[:alert] = "Unable to save post"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to posts_path
      flash[:alert] = "Your post has been successfully updated"
    else
      flash[:alert] = "Unable to update post"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    user = User.find_by(id: session[:user_id])
    redirect_to new_login_path unless user
    @user = user
    @post = Post.find_by(id: params[:id])
  end

  def destroy
  end

  def index
    @posts = Post.all
  end

  def show
    @user = User.find_by(id: session[:user_id])
    @post = Post.find_by(id: params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_login_path
    else
      flash[:alert] = "Unable to Sign the User up!"
      render :new, status: :unprocessable_entity
    end
  end

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboards/index.html.erb
<h1>Welcome, <%= @user.name %></h1>
<p>Check out the blogs written by you or other people by going to /posts.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogWithAuthentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/new.html.erb
<h1>Login!</h1>
<%= form_with model: @user, url: logins_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Login" %>
  </div>
<%end%>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.submit "Update" %>
  </div>
<%end%>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% @posts.each do |post| %>
  <%=link_to post do%>
    <p><%= post.title %> <br>
      : <%= post.user.name %></p>
  <%end%>
<%end%>

app/views/posts/new.html.erb
<h1>Create new Post</h1>
<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
    <%= form.hidden_field :user_id, value: @user.id %>
  </div>
  <div>
    <%= form.submit "Save" %>
  </div>
<%end%>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<br>
By - <%= @post.user.name %>
<br>
<br>
<% if @user%>
  <%= link_to "Edit post", edit_post_path(@post.id) %>
<%end%>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>